Repository COS301-SE-2024/Dispute-Resolution-Engine, pull requests merged in 2024-08, with the labels that each got.

#295 fix/checks uppercase and lower case Bearer
  api/middleware/jwt.go
Labels: service

#313 Fest/dispure proceedings logger
  api/auditLogger/disputeProceedingsLogger.go
  api/handlers/archive.go
  api/handlers/archive_test.go
  api/handlers/authentication.go
  api/handlers/dispute/dispute.go
  api/handlers/experts.go
  api/handlers/handlers.go
  api/models/models.go
Labels: service

#319 Release 20240807
  api/auditLogger/disputeProceedingsLogger.go
  api/handlers/archive.go
  api/handlers/archive_test.go
  api/handlers/authentication.go
  api/handlers/dispute/dispute.go
  api/handlers/dispute/dispute_test.go
  api/handlers/dispute/model.go
  api/handlers/experts.go
  api/handlers/handlers.go
  api/handlers/notifications/notifications.go
  api/middleware/jwt.go
  api/models/models.go
  api/models/requestModels.go
  api/models/utilityModels.go
  dre-docs/docs/api-contracts/Authentication.md
  frontend/package.json
  frontend/src/app/signup/page.tsx
  frontend/src/components/form/country-select.tsx
  frontend/src/components/form/language.select.tsx
  frontend/src/components/form/signup-form.tsx
  frontend/src/components/ui/form-client.tsx
  frontend/src/components/ui/radio-group.tsx
  frontend/src/lib/actions/auth.ts
  frontend/src/lib/api/index.ts
  frontend/src/lib/interfaces/auth.ts
  frontend/src/lib/schema/auth.ts
  frontend/yarn.lock
  initdb/init.sql
Labels: cicd

#322 fix: bandaid fix for expert assignment on dispute creation
  api/handlers/dispute/dispute.go
  api/handlers/dispute/model.go
  api/handlers/experts.go
Labels: service

#335 Added table
  initdb/init.sql
Labels: backend

#338 fix: I did a thing
  frontend/src/lib/actions/dispute.ts
Labels: service

#339 Feat/more tests
  api/auditLogger/disputeProceedingsLogger.go
  api/handlers/archive_test.go
  api/handlers/authentication.go
  api/handlers/dispute/dispute.go
  api/handlers/dispute/dispute_test.go
  api/handlers/dispute/model.go
  api/handlers/experts.go
  api/handlers/handlers.go
  api/main.go
Labels: service

#346 Feat/more tests
  api/handlers/archive_test.go
  api/handlers/authentication.go
  api/handlers/handlers.go
  api/handlers/user.go
  api/handlers/user_test.go
  api/handlers/utils_test.go
Labels: service
