Repository COS301-SE-2024/Dispute-Resolution-Engine, pull requests merged in 2024-09, with the labels that each got.

#391 Feat/database cleanup
  api/handlers/authentication.go
  api/handlers/dispute/model.go
  api/handlers/experts.go
  api/models/models.go
  initdb/init.sql
Labels: backend

#394 Fix/backend issues v1
  initdb/init.sql
Labels: backend

#396 Feat/workflow designer
  frontend/package.json
  frontend/src/app/workflow/CustomEdge.tsx
  frontend/src/app/workflow/CustomNode.tsx
  frontend/src/app/workflow/EventSection.tsx
  frontend/src/app/workflow/TimerCheckbox.tsx
  frontend/src/app/workflow/page.tsx
  frontend/src/components/ui/checkbox.tsx
  frontend/src/lib/types.ts
  frontend/yarn.lock
Labels: frontend

#411 Database fixes
  initdb/init.sql
Labels: backend

#412 Feat/admin services
  api/handlers/dispute/dispute.go
  api/handlers/dispute/dispute_test.go
  api/handlers/dispute/model.go
  api/models/models.go
  api/models/requestModels.go
  api/models/responseModels.go
  api/models/utilityModels.go
  initdb/init.sql
Labels: service

#452 Fix/dispute creation
  api/handlers/dispute/dispute.go
  api/models/requestModels.go
  frontend/yarn.lock
Labels: backend

#458 Feat/view expert rejections
  api/handlers/dispute/dispute.go
  api/handlers/dispute/dispute_test.go
  api/handlers/dispute/model.go
  api/models/models.go
  api/models/requestModels.go
  docs/docs/api-contracts/Disputes.md
  initdb/init.sql
Labels: service

#456 Feat/expert objection update
  api/handlers/dispute/dispute.go
  api/handlers/dispute/dispute_test.go
  api/handlers/dispute/model.go
  api/main.go
Labels: service

#463 Feat/workflow state machine
  api/handlers/dispute/dispute.go
  api/handlers/user_test.go
  api/handlers/workflow/model.go
  api/handlers/workflow/workflow.go
  api/handlers/workflow/workflow_test.go
  api/main.go
  api/middleware/jwt.go
  api/models/models.go
  api/models/requestModels.go
  compose.yaml
  docs/docs/api-contracts/Workflow.md
  docs/docs/dev-docs/api-contracts/Workflow.md
  initdb/init.sql
  orchestrator/controller/controller.go
  orchestrator/db/db.go
  orchestrator/db/models.go
  orchestrator/go.mod
  orchestrator/go.sum
  orchestrator/handlers/handler.go
  orchestrator/main.go
  orchestrator/scheduler/scheduler.go
  orchestrator/scheduler/scheduler_test.go
  orchestrator/statemachine/statemachine.go
  orchestrator/statemachine/statemachine_test.go
  orchestrator/templates/domain_template.json
  orchestrator/templates/v2.json
  orchestrator/templates/workflow.json
  orchestrator/utilities/utilities_test.go
  orchestrator/workflow/requestModels.go
  orchestrator/workflow/workflow.go
  orchestrator/workflow/workflowAPI.go
  orchestrator/workflow/workflowAPI_test.go
  orchestrator/workflow/workflowDbQueries.go
  orchestrator/workflow/workflow_test.go
  test.html
Labels: testing, backend, service

#475 Feat/ticket services
  api/handlers/ticket/model.go
  api/handlers/ticket/ticket.go
  api/main.go
  api/models/models.go
  api/models/requestModels.go
  api/models/responseModels.go
  api/models/utilityModels.go
  docs/docs/dev-docs/api-contracts/Admin.md
  docs/docs/dev-docs/api-contracts/Tickets.md
Labels: service

#483 Feat/admin disputes experts
  api/handlers/dispute/dispute_test.go
  api/handlers/dispute/model.go
  api/handlers/ticket/model.go
  api/models/responseModels.go
  api/models/utilityModels.go
  docs/docs/dev-docs/api-contracts/Admin.md
Labels: service

#485 Workflow email events
  api/handlers/dispute/dispute_test.go
  api/handlers/notifications/notifications.go
  api/handlers/orchestratorNotification/orchestartorNotification.go
  api/handlers/workflow/workflow_test.go
  api/main.go
  api/models/requestModels.go
  orchestrator/controller/controller.go
  orchestrator/handlers/handler.go
  orchestrator/main.go
  orchestrator/statemachine/statemachine.go
  orchestrator/utilities/utilities.go
  orchestrator/workflow/workflow.go
Labels: enhancement

#487 Feat/triggers endpoint
  api/handlers/workflow/model.go
  api/handlers/workflow/workflow.go
  api/handlers/workflow/workflow_test.go
  api/models/responseModels.go
  orchestrator/handlers/handler.go
  orchestrator/main.go
  orchestrator/workflow/workflow.go
Labels: service

#486 Feat/reset endpoint update
  api/handlers/workflow/model.go
  api/handlers/workflow/workflow.go
  api/handlers/workflow/workflow_test.go
  orchestrator/handlers/handler.go
Labels: service

#490 Feat/convert wf to graph
  admin-frontend/package.json
  admin-frontend/src/app/(pages)/workflows/designer/CustomEdge.tsx
  admin-frontend/src/app/(pages)/workflows/designer/page.tsx
  admin-frontend/src/lib/api/workflow.ts
  admin-frontend/src/lib/types/workflow.ts
  admin-frontend/yarn.lock
Labels: frontend

#510 Feat/analytics update
  api/handlers/adminAnalytics/analytics.go
  api/handlers/adminAnalytics/analytics_test.go
  api/handlers/adminAnalytics/model.go
  api/handlers/archive.go
  api/main.go
  api/models/requestModels.go
  initdb/init.sql
Labels: service

#513 feat? added contracts for analytics
  docs/docs/dev-docs/api-contracts/Analytics.md
Labels: service

#514 Fix/api fixes 2024 09 29
  api/handlers/adminAnalytics/model.go
  api/handlers/dispute/dispute.go
  api/handlers/dispute/dispute_test.go
  api/handlers/dispute/model.go
  api/models/models.go
  initdb/init.sql
Labels: service

#519 Improve Help Page
  docs/docs/api-contracts/Archive.md
  docs/docs/api-contracts/Authentication.md
  docs/docs/api-contracts/Disputes.md
  docs/docs/api-contracts/Expert.md
  docs/docs/api-contracts/README.md
  docs/docs/api-contracts/User.md
  docs/docs/api-contracts/Workflow.md
  docs/docs/api-contracts/_category_.json
  docs/docs/user-docs/helppage.md
Labels: enhancement

#526 Hotfix/e2e tests. Don't want to deal with it deploying
  .github/workflows/deployment.yaml
  frontend/cypress.config.ts
  frontend/cypress/e2e/archive.cy.tsx
  frontend/cypress/e2e/dispute.cy.tsx
  frontend/cypress/e2e/login.cy.tsx
  frontend/cypress/e2e/ticketing.cy.tsx
  frontend/cypress/e2e/workflows.cy.tsx
  frontend/src/components/navbar.tsx
Labels: testing

#532 Feat/orch triggers
  api/handlers/dispute/dispute.go
  api/handlers/dispute/dispute_test.go
  api/handlers/dispute/model.go
  api/handlers/notifications/notifications.go
  api/handlers/orchestratorNotification/orchestartorNotification.go
  api/handlers/workflow/workflow_test.go
  api/models/requestModels.go
  api/models/responseModels.go
  orchestrator/handlers/handler.go
  orchestrator/statemachine/statemachine.go
  orchestrator/templates/demo_flow.json
  orchestrator/utilities/utilities.go
  orchestrator/workflow/workflow.go
Labels: service

#534 feat: emails are formatted
  api/handlers/notifications/notifications.go
Labels: service
