Repository COS301-SE-2024/Dispute-Resolution-Engine, pull requests merged in 2024-06, with the labels that each got.

#40 Initial Disputes UI
  frontend/package.json
  frontend/src/app/disputes/[id]/page.tsx
  frontend/src/app/disputes/create/page.tsx
  frontend/src/app/disputes/layout.tsx
  frontend/src/app/disputes/page.tsx
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/components/ui/separator.tsx
  frontend/src/components/ui/tabs.tsx
  frontend/src/components/ui/textarea.tsx
  frontend/yarn.lock
Labels: enhancement, frontend

#51 Add loader.tsx page
  frontend/src/app/loading.tsx
  frontend/src/app/page.tsx
Labels: enhancement, frontend

#58 Add functional requirements
  docs/SoftwareRequirements.md
Labels: documentation

#61 Feat/technology requirements
  docs/TechnologyRequirements.md
Labels: documentation

#59 Add Quality Requirements and Architectural Patterns
  docs/Architecture.md
  docs/QualityRequirements.md
Labels: documentation

#68 Feat/readme
  .gitignore
  README.md
  docs/banner.svg
Labels: documentation

#69 Feat/documentation
  .gitignore
  README.md
  docs/Architecture.md
  docs/OWASP.md
  docs/QualityRequirements.md
  docs/SRBrief.md
  docs/SoftwareRequirements.md
  docs/TechnologyRequirements.md
  docs/UserStories.md
  docs/api-contracts/userEndpoint.md
  docs/banner.svg
Labels: documentation

#122 Add init.sql to compose postgres container
  .gitignore
  compose.yaml
  initdb/init.sql
Labels: enhancement, backend

#130 Feat/api roles
  api/handlers/authentication.go
  api/middleware/jwt.go
  api/middleware/roles.go
Labels: service

#135 Quality requirements quantification tables
  docs/QualityRequirements.md
Labels: documentation

#141 Add redis to compose.yaml
  compose.yaml
Labels: backend

#144 Feat/api disputes
  api/db/db.go
  api/handlers/authentication.go
  api/handlers/dispute.go
  api/handlers/user.go
  api/models/models.go
  api/models/requestModels.go
  docs/api-contracts/Authentication.md
  docs/api-contracts/User.md
Labels: backend, service

#161 Technology choices
  docs/TechnologyRequirements.md
Labels: documentation

#162 Feat/integrate create dispute
  api/handlers/dispute.go
  api/main.go
  api/middleware/cors.go
  api/middleware/jwt.go
  api/models/models.go
  api/models/responseModels.go
  api/utilities/utility.go
  docs/api-contracts/Disputes.md
  frontend/src/app/disputes/create/CreateDisputeClient.tsx
  frontend/src/app/disputes/create/page.tsx
  frontend/src/lib/api/dispute.ts
  frontend/src/lib/interfaces/dispute.ts
Labels: service
