Repository COS301-SE-2024/Dispute-Resolution-Engine, pull requests merged in 2024-07, with the labels that each got.

#198 Merge Prometheus, Grafana & cAdvisor containers
  compose.yaml
  prometheus.yml
Labels: backend

#229 Fix/login
  api/handlers/authentication.go
  api/models/utilityModels.go
Labels: service

#234 File Downloads
  api/handlers/dispute.go
  api/main.go
  compose.yaml
  frontend/src/app/disputes/[id]/client-page.tsx
Labels: service

#243 Fix/dispute get
  api/handlers/dispute.go
Labels: service

#240 Updated tables for logs, tagging, categorizing
  initdb/init.sql
Labels: backend

#247 Fix/api struct fix
  api/handlers/dispute.go
  api/models/models.go
  frontend/src/lib/api/dispute.ts
Labels: service

#261 Feat/error page
  frontend/src/app/error.tsx
  frontend/src/app/page.tsx
  frontend/src/lib/api/dispute.ts
Labels: frontend

#267 Fix/create dispute
  api/handlers/dispute.go
Labels: service

#279 Fix/expert rejection with reason
  api/handlers/dispute.go
  api/models/models.go
  api/models/requestModels.go
  docs/api-contracts/Disputes.md
Labels: service

#289 Feat/middleware interface
  .github/workflows/deployment.yaml
  api/handlers/authentication.go
  api/handlers/dispute/dispute.go
  api/handlers/dispute/model.go
  api/handlers/experts.go
  api/handlers/handlers.go
  api/handlers/user.go
  api/handlers/user_test.go
  api/main.go
  api/middleware/cors.go
  api/middleware/interfaces.go
  api/middleware/jwt.go
  api/middleware/jwt_test.go
  api/middleware/roles.go
  api/models/responseModels.go
  compose.yaml
  frontend/src/app/disputes/layout.tsx
  frontend/src/app/disputes/link.tsx
  frontend/src/app/splash/splash.tsx
  frontend/src/components/navbar.tsx
Labels: service
